export const TILES = {
  0: {
    name: "GRASS",
    className: "grass",
    weight: 1,
    isObstacle: false,
    blocksVision: false,
  },
  1: {
    name: "CLIFF",
    className: "cliff",
    weight: Infinity,
    isObstacle: true,
    blocksVision: true,
  },
  2: {
    name: "DOOR",
    className: "door",
    weight: 1,
    isObstacle: false,
    blocksVision: true,
  },
  3: {
    name: "FENCE_HORI",
    className: "fence_hori",
    weight: Infinity,
    isObstacle: true,
    blocksVision: false,
  },
  4: {
    name: "FENCE_VERT",
    className: "fence_vert",
    weight: Infinity,
    isObstacle: true,
    blocksVision: false,
  },
  5: {
    name: "FLOOR_PLANKS",
    className: "floor_planks",
    weight: 1,
    isObstacle: false,
    blocksVision: false,
  },
  6: {
    name: "FLOOR_STONE",
    className: "floor_stone",
    weight: 1,
    isObstacle: false,
    blocksVision: false,
  },
  7: {
    name: "FLOOR_WOOD",
    className: "floor_wood",
    weight: 1,
    isObstacle: false,
    blocksVision: false,
  },
  8: {
    name: "FLOOR_CARPET",
    className: "floor_carpet",
    weight: 1,
    isObstacle: false,
    blocksVision: false,
  },
  9: {
    name: "FLOWERS",
    className: "flowers",
    weight: 1,
    isObstacle: false,
    blocksVision: false,
  },
  10: {
    name: "GATE",
    className: "gate",
    weight: 1,
    isObstacle: false,
    blocksVision: true,
  },
  11: {
    name: "ABYSS",
    className: "abyss",
    weight: Infinity,
    isObstacle: true,
    blocksVision: false,
  },
  12: {
    name: "LAVA",
    className: "lava",
    weight: Infinity,
    isObstacle: true,
    blocksVision: false,
  },
  13: {
    name: "MINE",
    className: "mine",
    weight: Infinity,
    isObstacle: true,
    blocksVision: false,
  },
  14: {
    name: "PATH",
    className: "path",
    weight: 1,
    isObstacle: false,
    blocksVision: false,
  },
  15: {
    name: "REDWALL",
    className: "redwall",
    weight: Infinity,
    isObstacle: true,
    blocksVision: true,
  },
  16: {
    name: "TREE",
    className: "tree",
    weight: Infinity,
    isObstacle: true,
    blocksVision: true,
  },
  17: {
    name: "WALL",
    className: "wall",
    weight: Infinity,
    isObstacle: true,
    blocksVision: true,
  },
  18: {
    name: "WATER",
    className: "water",
    weight: Infinity,
    isObstacle: true,
    blocksVision: false,
  },
  19: {
    name: "WELL",
    className: "well",
    weight: Infinity,
    isObstacle: true,
    blocksVision: true,
  },
};
